services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: hub-homepage
    restart: unless-stopped
    ports:
      - "3005:3000"
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=100.72.95.93:3005,100.72.95.93,localhost:3005,127.0.0.1:3005,hub.proxy
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
